### ISSUE TITLE
Permission issue on demo files

### ISSUE THREAD

**Issue by rouault** [boundlessgeo/cogj-spec#2]
https://s3.amazonaws.com/cogeojson/Cadastral.json and https://s3.amazonaws.com/cogeojson/Cadastral.json.coj lead to a 403 Permission denied

**Comment by tingold** [comment]
Sorry -- file names changed in last upload.  New ones are below -- will update docs as well. 

https://s3.amazonaws.com/cogeojson/Cadastral.geojson.coj
https://s3.amazonaws.com/cogeojson/Cadastral.geojson
