### ISSUE TITLE
Using JSON Text Sequences or JSON-ND

### ISSUE THREAD

**Issue by rouault** [boundlessgeo/cogj-spec#3]
The current specification could be improved to make the COGeojson format a bit more standard to existing readers supporting GeoJSON sequences, while keeping the indexing header.

For example by conforming to https://tools.ietf.org/html/rfc8142 to separate the header and each FeatureCollection, ie by inserting a RS = 0x1e character in front of each part, and suffix them by LF = 0x0A
As a complement, instead of wrapping the Features in a FeatureCollection, the Feature object themselves could be just a sequence of Feature object prefixed by RS.

An alternative to using the RS prefix in front of each JSON text is to just postfix with LF, to produce JSON-ND: http://ndjson.org. That implies that each JSON text does not use pretty printing of course.

**Comment by tingold** [comment]
Thanks for this - I didn't know about 8142. I had seen a post a while ago about streaming GeoJSON but it seemed like we were tackling different problems.  It didn't occur to me to combine the two approaches. 

Is there a downside to allowing both Features and FeatureCollections in the indexed stream? It seems to me the flexibility would be useful.
Either way, this should be easy to change and a good idea.
